name: WindSpigot Build

on:
  push:

jobs:
  cleanup-and-build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip]')"
    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      run: mvn clean package --file $GITHUB_WORKSPACE/pom.xml
      
    - name: Upload Server Artifact
      uses: actions/upload-artifact@v2.2.0
      with:
        name: WindSpigot-server
        path: ${{ github.workspace }}/WindSpigot-Server/target/WindSpigot.jar

    - name: Upload API Artifact
      uses: actions/upload-artifact@v2.2.0
      with:
        name: WindSpigot-API
        path: ${{ github.workspace }}/WindSpigot-API/target/WindSpigot-API.jar
